#!/usr/bin/python3

import argparse
import subprocess


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('device')
    args = parser.parse_args()

    # FIXME: add an "are you REALLY SURE?" prompt here.

    subprocess.check_call(['wipefs', args.device])
    subprocess.call(['blkdiscard', args.device])  # usually fails; we don't care.
    subprocess.check_call(['parted',
                           '--script',
                           '--align=optimal',
                           args.device] +
                          'mklabel msdos'.split() +
                          'mkpart primary 0% 128MiB '.split() +
                          'mkpart primary 128MiB 100%'.split())
    subprocess.check_call(['mkfs', '--type=vfat', '--label=FSDriver', '{}1'.format(args.device)])
    subprocess.check_call(['mkfs', '--type=ext3', '--label=DatasafeLite', '{}2'.format(args.device)])
    subprocess.check_call('install -dm700 -oroot -groot /mnt/umount-me'.split())
    subprocess.check_call('mount LABEL=FSDriver /mnt/umount-me'.split())
    # FIXME: for fuck's sake, AT LEAST find an HTTPS link!
    subprocess.check_call('wget --directory-prefix=/mnt/umount-me http://www.fs-driver.org/download/Ext2IFS_1_12.exe'.split())
    with open('/mnt/umount-me/README.txt', 'w') as f:
        print(_fsdriver_readme_str, f)
    subprocess.check_call('umount LABEL=FSDriver'.split())

    subprocess.check_call('mount LABEL=DatasafeLite /mnt/umount-me'.split())
    # rsnapshot checks that this dir exists before it backs up into it
    subprocess.check_call('install -dm755 -oroot -groot /mnt/umount-me/DATA'.split())
    with open('/mnt/umount-me/README.txt', 'w') as f:
        print(_datasafelite_readme_str, f)
    subprocess.check_call('umount LABEL=DatasafeLite'.split())


# NOTE: copy-pasted from what I found on AMC's HDD.
# (Except for the smart quotes, which I asciified, since this file will probably be viewed in notepad.)
# FIXME: should also ensure CRLF, not LF, for same reason!
_fsdriver_readme_str = '''
Installing Ext2 driver on Windows

Start installing the driver found on the readable part of the external
drive. At the time of writing (13 May 2014), this was named "Ext2IFS_1_11a.exe". This driver
can also be obtained from http://www.fs-driver.org/download.html

Go through the installation, mostly just clicking Next, as most options dont
need to be changed. Items that do need changing are:

* Enable the read-only option.
* Accepting the license agreement.
* Checking the option on the "Drive Letters" window that says "Assign drive
  letter automatically upon plugging in a device the first time".

Once the installation is finished, you will likely have to safely remove the
drive, and plug it back in so that the software detects it and assigns the data
partition a drive letter.

If for some reason this still fails, go to the "IFS Drives" menu item in
Control Panel (you may need to switch from category view, to all items/classic
view in Control Panel to see this), and it should list the label of the new
partition, along with a drop-down box allowing you to manually assign it a
drive letter. Also confirm that the "Assign drive letter automatically"
checkbox down the bottom is checked.
'''

_datasafelite_readme_str = '''
FIXME
'''

if __name__ == '__main__':
    main()
